"""
features/address_similarity.py

Commit 2.2 - Address Similarity Features
Computes pairwise address similarity metrics strictly on the normalized_address fields
for every candidate pair generated by the blocking stage.

Metrics computed:
  - address_token_jaccard  : Token Jaccard overlap on address words (float [0, 1])
  - address_tfidf_cosine   : TF-IDF cosine similarity from an address-only vectorizer (float [0, 1])
  - has_address            : Boolean flag (True if both records have a valid, non-empty address,
                             False if either record has an empty/missing address)

Crucial Edge Case Handling:
  - If either address in a pair is missing, empty, NaN, or contains no alphanumeric tokens,
    similarity scores output the sentinel value -1.0 (never crash or silently return 0.0).
  - has_address is set to False for such rows, allowing downstream classifiers
    (e.g., LightGBM) to explicitly discount address features for those pairs.

Return value:
  pd.DataFrame keyed by (source1_entity_id, candidate_entity_id) with:
    - source1_entity_id      (str)
    - candidate_entity_id    (str)
    - address_token_jaccard  (float)
    - address_tfidf_cosine   (float)
    - has_address            (bool)
"""

from __future__ import annotations

import re
from typing import Any, Dict, Iterable, List, Optional, Set, Union

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer


# ---------------------------------------------------------------------------
# Low-level helpers & Edge-case handling
# ---------------------------------------------------------------------------


def _safe_str(text: Any) -> str:
    """Returns a clean lowercase string; None / NaN / non-str -> empty string."""
    if text is None:
        return ""
    if not isinstance(text, str):
        try:
            import math
            if math.isnan(float(text)):
                return ""
        except (TypeError, ValueError):
            pass
        return str(text).strip().lower()
    return text.strip().lower()


def _is_empty_or_sparse(text: Any) -> bool:
    """
    Checks if an address is empty, NaN, or completely lacks word tokens.
    Day-1 EDA identified missing/sparse addresses that require sentinel handling.
    """
    cleaned = _safe_str(text)
    if not cleaned or cleaned in {"nan", "null", "none"}:
        return True
    tokens = re.findall(r"\w+", cleaned)
    return len(tokens) == 0


def address_token_jaccard(a: Any, b: Any) -> float:
    """
    Computes token Jaccard similarity between two address strings.

    Returns:
      -1.0 if either address is missing/empty/sparse (sentinel value).
      float in [0.0, 1.0] representing intersection / union of tokens.
    """
    if _is_empty_or_sparse(a) or _is_empty_or_sparse(b):
        return -1.0

    tokens_a: Set[str] = set(re.findall(r"\w+", _safe_str(a)))
    tokens_b: Set[str] = set(re.findall(r"\w+", _safe_str(b)))

    if not tokens_a or not tokens_b:
        return -1.0

    intersection = len(tokens_a & tokens_b)
    union = len(tokens_a | tokens_b)
    if union == 0:
        return -1.0

    return round(float(intersection) / float(union), 6)


# ---------------------------------------------------------------------------
# Address-Only TF-IDF Vectorizer
# ---------------------------------------------------------------------------


def create_address_vectorizer() -> TfidfVectorizer:
    """
    Instantiates a dedicated TF-IDF vectorizer strictly configured for addresses.
    Completely independent from any name vectorizer.
    """
    return TfidfVectorizer(
        token_pattern=r"(?u)\b\w+\b",
        ngram_range=(1, 2),
        min_df=1,
        sublinear_tf=True,
        norm="l2",
    )


def fit_address_vectorizer(
    corpus: Iterable[str],
    vectorizer: Optional[TfidfVectorizer] = None,
) -> TfidfVectorizer:
    """
    Fits an address-only TF-IDF vectorizer over an iterable of address strings.
    Ignores empty/sparse addresses during fitting.
    """
    if vectorizer is None:
        vectorizer = create_address_vectorizer()

    valid_corpus = [
        _safe_str(addr)
        for addr in corpus
        if not _is_empty_or_sparse(addr)
    ]
    if not valid_corpus:
        valid_corpus = ["address"]

    vectorizer.fit(valid_corpus)
    return vectorizer


def address_tfidf_cosine(
    a: Any,
    b: Any,
    vectorizer: Optional[TfidfVectorizer] = None,
) -> float:
    """
    Computes TF-IDF cosine similarity between two address strings.

    Returns:
      -1.0 if either address is missing/empty/sparse (sentinel value).
      float in [0.0, 1.0] when both addresses are valid.
    """
    if _is_empty_or_sparse(a) or _is_empty_or_sparse(b):
        return -1.0

    clean_a = _safe_str(a)
    clean_b = _safe_str(b)

    if clean_a == clean_b:
        return 1.0

    if vectorizer is None:
        vec = create_address_vectorizer()
        try:
            mat = vec.fit_transform([clean_a, clean_b])
            cos_sim = float(mat[0].dot(mat[1].T).toarray()[0, 0])
            return round(max(0.0, min(1.0, cos_sim)), 6)
        except Exception:
            return 0.0
    else:
        try:
            vec_a = vectorizer.transform([clean_a])
            vec_b = vectorizer.transform([clean_b])
            cos_sim = float(vec_a.dot(vec_b.T).toarray()[0, 0])
            return round(max(0.0, min(1.0, cos_sim)), 6)
        except Exception:
            return 0.0


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def compute_address_similarity_features(
    candidate_pairs: Union[List[Dict[str, str]], pd.DataFrame],
    s1_df: pd.DataFrame,
    s2_s3_df: pd.DataFrame,
    address_col: str = "normalized_address",
    vectorizer: Optional[TfidfVectorizer] = None,
) -> pd.DataFrame:
    """
    Computes address similarity features for every candidate pair.

    Parameters
    ----------
    candidate_pairs : list of dicts or pd.DataFrame with keys 'source1_entity_id'
                      and 'candidate_entity_id'
    s1_df           : Source-1 DataFrame (must contain 'entity_id' and address column)
    s2_s3_df        : Source-2 + Source-3 DataFrame (same schema)
    address_col     : column name holding the address (falls back to clean_address
                      or business_address if not found)
    vectorizer      : optional pre-fitted address-only TfidfVectorizer. If None,
                      one is automatically fitted over all addresses in s1_df and s2_s3_df.

    Returns
    -------
    pd.DataFrame keyed by (source1_entity_id, candidate_entity_id) with columns:
      - source1_entity_id
      - candidate_entity_id
      - address_token_jaccard
      - address_tfidf_cosine
      - has_address
    """
    # Resolve address column with graceful fallbacks
    def _resolve_col(df: pd.DataFrame) -> str:
        for c in [address_col, "normalized_address", "clean_address", "business_address"]:
            if c in df.columns:
                return c
        raise KeyError(
            f"Could not find address column in DataFrame. Checked: {[address_col, 'normalized_address', 'clean_address', 'business_address']}"
        )

    s1_col = _resolve_col(s1_df)
    cand_col = _resolve_col(s2_s3_df)

    s1_addr_lookup: Dict[str, str] = (
        s1_df.set_index("entity_id")[s1_col]
        .fillna("")
        .astype(str)
        .to_dict()
    )
    cand_addr_lookup: Dict[str, str] = (
        s2_s3_df.set_index("entity_id")[cand_col]
        .fillna("")
        .astype(str)
        .to_dict()
    )

    # Normalize candidate_pairs into records iterable
    if isinstance(candidate_pairs, pd.DataFrame):
        pairs_iter: List[Dict[str, str]] = candidate_pairs[
            ["source1_entity_id", "candidate_entity_id"]
        ].to_dict(orient="records")
    else:
        pairs_iter = candidate_pairs

    # Ensure address-only vectorizer is fitted
    if vectorizer is None:
        all_unique_addresses = list(
            set(s1_addr_lookup.values()) | set(cand_addr_lookup.values())
        )
        vectorizer = fit_address_vectorizer(all_unique_addresses)

    # Pre-vectorize unique non-empty addresses for O(1) pairwise cosine lookup
    unique_non_empty = [
        addr for addr in (set(s1_addr_lookup.values()) | set(cand_addr_lookup.values()))
        if not _is_empty_or_sparse(addr)
    ]
    if unique_non_empty:
        tfidf_matrix = vectorizer.transform(unique_non_empty)
        addr_to_vec = {
            addr: tfidf_matrix[i]
            for i, addr in enumerate(unique_non_empty)
        }
    else:
        addr_to_vec = {}

    rows: List[Dict[str, Any]] = []
    for pair in pairs_iter:
        s1_id = str(pair["source1_entity_id"])
        cand_id = str(pair["candidate_entity_id"])

        addr_a = s1_addr_lookup.get(s1_id, "")
        addr_b = cand_addr_lookup.get(cand_id, "")

        is_a_empty = _is_empty_or_sparse(addr_a)
        is_b_empty = _is_empty_or_sparse(addr_b)

        if is_a_empty or is_b_empty:
            rows.append(
                {
                    "source1_entity_id": s1_id,
                    "candidate_entity_id": cand_id,
                    "address_token_jaccard": -1.0,
                    "address_tfidf_cosine": -1.0,
                    "has_address": False,
                }
            )
        else:
            jaccard = address_token_jaccard(addr_a, addr_b)

            vec_a = addr_to_vec.get(addr_a)
            vec_b = addr_to_vec.get(addr_b)
            if vec_a is not None and vec_b is not None:
                cos_val = float(vec_a.dot(vec_b.T).toarray()[0, 0])
                tfidf_cos = round(max(0.0, min(1.0, cos_val)), 6)
            else:
                tfidf_cos = 0.0

            rows.append(
                {
                    "source1_entity_id": s1_id,
                    "candidate_entity_id": cand_id,
                    "address_token_jaccard": jaccard,
                    "address_tfidf_cosine": tfidf_cos,
                    "has_address": True,
                }
            )

    return pd.DataFrame(
        rows,
        columns=[
            "source1_entity_id",
            "candidate_entity_id",
            "address_token_jaccard",
            "address_tfidf_cosine",
            "has_address",
        ],
    )
