"""
features/name_similarity.py

Commit 2.1 - Name Similarity Features
Computes pairwise string distance metrics on normalized_name fields
for every candidate pair generated by the blocking stage.

Metrics computed:
  - jaro_winkler_similarity   : Jaro-Winkler similarity (float [0, 1])
  - normalized_levenshtein    : 1 - edit_distance / max(len_a, len_b), sentinel -1 for empty pairs
  - monge_elkan_similarity    : Monge-Elkan average best-token match (float [0, 1])

All values are floats in [0, 1]. Empty / null names return 0.0 (or -1 sentinel for
normalized_levenshtein when both strings are empty).

Return value:
  pd.DataFrame with columns:
    source1_entity_id    (str)
    candidate_entity_id  (str)
    jaro_winkler_similarity     (float)
    normalized_levenshtein      (float)
    monge_elkan_similarity      (float)
"""

from __future__ import annotations

from typing import Any, Dict, List, Set

import jellyfish
import pandas as pd


# ---------------------------------------------------------------------------
# Low-level metric helpers
# ---------------------------------------------------------------------------


def _safe_str(text: Any) -> str:
    """Returns a clean lowercase string; None / NaN / non-str -> empty string."""
    if text is None:
        return ""
    if not isinstance(text, str):
        try:
            import math
            if math.isnan(float(text)):
                return ""
        except (TypeError, ValueError):
            pass
        return str(text).strip().lower()
    return text.strip().lower()


def jaro_winkler(a: str, b: str) -> float:
    """Jaro-Winkler similarity in [0, 1]. Returns 0.0 if either string is empty."""
    a, b = _safe_str(a), _safe_str(b)
    if not a or not b:
        return 0.0
    return round(jellyfish.jaro_winkler_similarity(a, b), 6)


def normalized_levenshtein(a: str, b: str) -> float:
    """
    Normalized Levenshtein: 1 - edit_distance / max(len_a, len_b).
    Returns -1.0 sentinel when both strings are empty (signals missing data
    to the downstream model via a separate has_name flag).
    """
    a, b = _safe_str(a), _safe_str(b)
    if not a and not b:
        return -1.0  # sentinel: both names missing
    max_len = max(len(a), len(b))
    dist = jellyfish.levenshtein_distance(a, b)
    return round(1.0 - dist / max_len, 6)


def monge_elkan(a: str, b: str) -> float:
    """
    Monge-Elkan similarity between two strings.

    Splits each string into tokens, then for every token in `a` finds the
    maximum Jaro-Winkler similarity against any token in `b`.
    Returns the average of these maximal similarities.

    Returns 0.0 if either string is empty.
    """
    a, b = _safe_str(a), _safe_str(b)
    if not a or not b:
        return 0.0

    tokens_a: List[str] = a.split()
    tokens_b: List[str] = b.split()

    if not tokens_a or not tokens_b:
        return 0.0

    total = 0.0
    for tok_a in tokens_a:
        best = max(
            jellyfish.jaro_winkler_similarity(tok_a, tok_b) for tok_b in tokens_b
        )
        total += best

    return round(total / len(tokens_a), 6)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def compute_name_similarity_features(
    candidate_pairs: List[Dict[str, str]],
    s1_df: pd.DataFrame,
    s2_s3_df: pd.DataFrame,
    name_col: str = "normalized_name",
) -> pd.DataFrame:
    """
    Computes name similarity features for every candidate pair.

    Parameters
    ----------
    candidate_pairs : list of dicts with keys 'source1_entity_id' and 'candidate_entity_id'
    s1_df           : Source-1 DataFrame (must contain 'entity_id' and `name_col`)
    s2_s3_df        : Source-2 + Source-3 DataFrame (same schema)
    name_col        : column name holding the pre-normalised business name

    Returns
    -------
    pd.DataFrame keyed by (source1_entity_id, candidate_entity_id) with three
    float similarity columns.
    """
    # Build fast lookup: entity_id -> normalized name
    s1_name_lookup: Dict[str, str] = (
        s1_df.set_index("entity_id")[name_col]
        .fillna("")
        .to_dict()
    )
    cand_name_lookup: Dict[str, str] = (
        s2_s3_df.set_index("entity_id")[name_col]
        .fillna("")
        .to_dict()
    )

    rows: List[Dict[str, Any]] = []
    for pair in candidate_pairs:
        s1_id = pair["source1_entity_id"]
        cand_id = pair["candidate_entity_id"]

        name_a = s1_name_lookup.get(s1_id, "")
        name_b = cand_name_lookup.get(cand_id, "")

        rows.append(
            {
                "source1_entity_id": s1_id,
                "candidate_entity_id": cand_id,
                "jaro_winkler_similarity": jaro_winkler(name_a, name_b),
                "normalized_levenshtein": normalized_levenshtein(name_a, name_b),
                "monge_elkan_similarity": monge_elkan(name_a, name_b),
            }
        )

    return pd.DataFrame(
        rows,
        columns=[
            "source1_entity_id",
            "candidate_entity_id",
            "jaro_winkler_similarity",
            "normalized_levenshtein",
            "monge_elkan_similarity",
        ],
    )
