"""schemas.py - Typed data contracts for the Business Entity Resolution pipeline.

Defines dataclasses, TypedDicts, and column schemas for:
(a) Normalized Record
(b) Candidate Pair
(c) Feature Row
(d) Final Submission Rows (matching_results.tsv and candidate_pairs.tsv)
"""

from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Literal, Optional, TypedDict

# =============================================================================
# 1. NORMALIZED RECORD SCHEMA
# =============================================================================


@dataclass
class NormalizedRecord:
    """Represents a business record after text normalization."""

    entity_id: str
    business_name: str
    business_address: str
    country: str
    normalized_name: str
    normalized_address: str

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class NormalizedRecordDict(TypedDict):
    entity_id: str
    business_name: str
    business_address: str
    country: str
    normalized_name: str
    normalized_address: str


NORMALIZED_RECORD_COLUMNS: List[str] = [
    "entity_id",
    "business_name",
    "business_address",
    "country",
    "normalized_name",
    "normalized_address",
]


# =============================================================================
# 2. CANDIDATE PAIR SCHEMA
# =============================================================================


@dataclass
class CandidatePair:
    """Represents a potential match pair generated by the blocking stage."""

    source1_entity_id: str
    candidate_entity_id: str
    source: Literal["S2", "S3", "unknown"] = "unknown"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class CandidatePairDict(TypedDict):
    source1_entity_id: str
    candidate_entity_id: str
    source: str


CANDIDATE_PAIR_COLUMNS: List[str] = [
    "source1_entity_id",
    "candidate_entity_id",
    "source",
]


# =============================================================================
# 3. FEATURE ROW SCHEMA
# =============================================================================


@dataclass
class FeatureRow:
    """Represents pairwise similarity features computed for a candidate pair."""

    source1_entity_id: str
    candidate_entity_id: str

    # --- Name Similarity Features ---
    exact_name_match: float = 0.0
    name_token_jaccard: float = 0.0
    name_3gram_similarity: float = 0.0
    name_prefix_match: float = 0.0
    name_len_diff_ratio: float = 0.0
    name_levenshtein_similarity: float = 0.0
    name_monge_elkan: float = 0.0

    # --- Address Similarity Features ---
    exact_address_match: float = 0.0
    address_token_jaccard: float = 0.0
    address_3gram_similarity: float = 0.0
    address_missing: float = 0.0

    # --- Domain / Geographic Features ---
    country_match: float = 0.0
    numeric_overlap_count: float = 0.0
    has_shared_pin: float = 0.0
    pin_prefix_match: float = 0.0

    # --- Target & Prediction Meta (Optional) ---
    label: Optional[int] = None
    prob_match: Optional[float] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class FeatureRowDict(TypedDict, total=False):
    source1_entity_id: str
    candidate_entity_id: str
    exact_name_match: float
    name_token_jaccard: float
    name_3gram_similarity: float
    name_prefix_match: float
    name_len_diff_ratio: float
    name_levenshtein_similarity: float
    name_monge_elkan: float
    exact_address_match: float
    address_token_jaccard: float
    address_3gram_similarity: float
    address_missing: float
    country_match: float
    numeric_overlap_count: float
    has_shared_pin: float
    pin_prefix_match: float
    label: Optional[int]
    prob_match: Optional[float]


FEATURE_COLUMNS: List[str] = [
    "exact_name_match",
    "name_token_jaccard",
    "name_3gram_similarity",
    "name_prefix_match",
    "name_len_diff_ratio",
    "name_levenshtein_similarity",
    "name_monge_elkan",
    "exact_address_match",
    "address_token_jaccard",
    "address_3gram_similarity",
    "address_missing",
    "country_match",
    "numeric_overlap_count",
    "has_shared_pin",
    "pin_prefix_match",
]


# =============================================================================
# 4. FINAL OUTPUT ROW SCHEMAS (TSV Submissions)
# =============================================================================


@dataclass
class MatchingResultRow:
    """Row schema for final matching_results.tsv (official evaluated file).

    matched_entity_ids is a comma-separated string of matched IDs (or empty for singletons).
    """

    source1_entity_id: str
    matched_entity_ids: str = ""

    def to_dict(self) -> Dict[str, str]:
        return asdict(self)


class MatchingResultDict(TypedDict):
    source1_entity_id: str
    matched_entity_ids: str


MATCHING_RESULTS_HEADER: List[str] = [
    "source1_entity_id",
    "matched_entity_ids",
]


@dataclass
class CandidatePairsRow:
    """Row schema for candidate_pairs.tsv (blocking candidates output).

    candidate_entity_ids is a comma-separated string of candidate IDs (or empty).
    """

    source1_entity_id: str
    candidate_entity_ids: str = ""

    def to_dict(self) -> Dict[str, str]:
        return asdict(self)


class CandidatePairsDict(TypedDict):
    source1_entity_id: str
    candidate_entity_ids: str


CANDIDATE_PAIRS_HEADER: List[str] = [
    "source1_entity_id",
    "candidate_entity_ids",
]
