"""schemas.py - Re-export from code/business_entity_resolution/src/schemas.py for flat src package imports."""
from code.business_entity_resolution.src.schemas import (
    NormalizedRecord,
    NormalizedRecordDict,
    NORMALIZED_RECORD_COLUMNS,
    CandidatePair,
    CandidatePairDict,
    CANDIDATE_PAIR_COLUMNS,
    FeatureRow,
    FeatureRowDict,
    FEATURE_COLUMNS,
    MatchingResultRow,
    MatchingResultDict,
    MATCHING_RESULTS_HEADER,
    CandidatePairsRow,
    CandidatePairsDict,
    CANDIDATE_PAIRS_HEADER,
)

__all__ = [
    "NormalizedRecord",
    "NormalizedRecordDict",
    "NORMALIZED_RECORD_COLUMNS",
    "CandidatePair",
    "CandidatePairDict",
    "CANDIDATE_PAIR_COLUMNS",
    "FeatureRow",
    "FeatureRowDict",
    "FEATURE_COLUMNS",
    "MatchingResultRow",
    "MatchingResultDict",
    "MATCHING_RESULTS_HEADER",
    "CandidatePairsRow",
    "CandidatePairsDict",
    "CANDIDATE_PAIRS_HEADER",
]
